# Generated by Django 5.0.3 on 2024-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.FileField(upload_to='test_cases/input_data/'),
        ),
    ]
